In [2]:
import tensorflow as tf
import numpy as np
from sklearn.metrics import confusion_matrix, precision_score, recall_score, f1_score
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense
from tensorflow.keras.datasets import mnist, fashion_mnist
from tensorflow.keras import layers, models 

In [3]:
#VGG architecture
def vgg():
    model = Sequential()

    #block 1
    model.add(Conv2D(64, (3,3), activation = 'relu', padding = 'same', input_shape = (28, 28, 1)))
    model.add(Conv2D(64, (3,3), activation = 'relu', padding = 'same'))
    model.add(MaxPooling2D((2,2), strides = (2,2)))

    #block 2
    model.add(Conv2D(128, (3,3), activation = 'relu', padding = 'same'))
    model.add(Conv2D(128, (3,3), activation = 'relu', padding = 'same'))
    model.add(MaxPooling2D((2,2), strides = (2,2)))

    #block 3
    model.add(Conv2D(256, (3,3), activation = 'relu', padding = 'same', input_shape = (28, 28, 1)))
    model.add(Conv2D(256, (3,3), activation = 'relu', padding = 'same'))
    model.add(Conv2D(256, (3,3), activation = 'relu', padding = 'same'))
    model.add(MaxPooling2D((2,2), strides = (2,2)))

    #block 4
    model.add(Conv2D(512, (3,3), activation = 'relu', padding = 'same'))
    model.add(Conv2D(512, (3,3), activation = 'relu', padding = 'same'))
    model.add(Conv2D(512, (3,3), activation = 'relu', padding = 'same'))
    model.add(MaxPooling2D((2,2), strides=(2,2)))

    #block 5
    model.add(Conv2D(512, (3,3), activation = 'relu', padding = 'same'))
    model.add(Conv2D(512, (3,3), activation = 'relu', padding = 'same'))
    model.add(Conv2D(512, (3,3), activation = 'relu', padding = 'same'))
    #model.add(MaxPooling2D((2,2), strides=(2,2)))
    
    #flattening
    model.add(Flatten())
    model.add(Dense(4096, activation = 'relu'))
    model.add(Dense(4096, activation = 'relu'))
    model.add(Dense(10, activation = 'softmax')) # output layer, 10 classes

    return model 
    
vgg_model = vgg()
vgg_model.summary()


y:\Python_installation\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv2d (Conv2D)                 │ (None, 28, 28, 64)     │           640 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_1 (Conv2D)               │ (None, 28, 28, 64)     │        36,928 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d (MaxPooling2D)    │ (None, 14, 14, 64)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_2 (Conv2D)               │ (None, 14, 14, 128)    │        73,856 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_3 (Conv2D)               │ (None, 14, 14, 128)    │       147,584 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_1 (MaxPooling2D)  │ (None, 7, 7, 128)      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_4 (Conv2D)               │ (None, 7, 7, 256)      │       295,168 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_5 (Conv2D)               │ (None, 7, 7, 256)      │       590,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_6 (Conv2D)               │ (None, 7, 7, 256)      │       590,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_2 (MaxPooling2D)  │ (None, 3, 3, 256)      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_7 (Conv2D)               │ (None, 3, 3, 512)      │     1,180,160 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_8 (Conv2D)               │ (None, 3, 3, 512)      │     2,359,808 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_9 (Conv2D)               │ (None, 3, 3, 512)      │     2,359,808 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_3 (MaxPooling2D)  │ (None, 1, 1, 512)      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_10 (Conv2D)              │ (None, 1, 1, 512)      │     2,359,808 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_11 (Conv2D)              │ (None, 1, 1, 512)      │     2,359,808 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_12 (Conv2D)              │ (None, 1, 1, 512)      │     2,359,808 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten (Flatten)               │ (None, 512)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 4096)           │     2,101,248 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 4096)           │    16,781,312 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 10)             │        40,970 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 33,637,066 (128.32 MB)

 Trainable params: 33,637,066 (128.32 MB)

 Non-trainable params: 0 (0.00 B)

In [12]:
#load mnist dataset
(x_train, y_train), (x_test, y_test) = mnist.load_data()

In [13]:
#preprocess-normalize
x_train = x_train/255.0
x_test = x_test/255.0

In [14]:
#convert label to categorical 
y_train = to_categorical(y_train, 10)
y_test = to_categorical(y_test, 10)

In [15]:
print("Shape of x_train:", x_train.shape)
print("Shape of y_train:", y_train.shape)
print("Shape of x_test:", x_test.shape)
print("Shape of y_test:", y_test.shape)

Shape of x_train: (60000, 28, 28)
Shape of y_train: (60000, 10)
Shape of x_test: (10000, 28, 28)
Shape of y_test: (10000, 10)


In [16]:
#compile and train model
vgg_model.compile(loss = 'categorical_crossentropy', optimizer = 'adam', metrics = ['accuracy'])
vgg_model.fit(x_train, y_train, validation_data=(x_test, y_test), epochs =10, batch_size = 200, verbose = True)

Epoch 1/10
300/300 ━━━━━━━━━━━━━━━━━━━━ 430s 1s/step - accuracy: 0.1112 - loss: 2.3017 - val_accuracy: 0.1135 - val_loss: 2.3010
Epoch 2/10
300/300 ━━━━━━━━━━━━━━━━━━━━ 665s 2s/step - accuracy: 0.1095 - loss: 2.3018 - val_accuracy: 0.1135 - val_loss: 2.3011
Epoch 3/10
300/300 ━━━━━━━━━━━━━━━━━━━━ 384s 1s/step - accuracy: 0.1135 - loss: 2.3011 - val_accuracy: 0.1135 - val_loss: 2.3012
Epoch 4/10
300/300 ━━━━━━━━━━━━━━━━━━━━ 313s 1s/step - accuracy: 0.1103 - loss: 2.3016 - val_accuracy: 0.1135 - val_loss: 2.3010
Epoch 5/10
300/300 ━━━━━━━━━━━━━━━━━━━━ 317s 1s/step - accuracy: 0.1132 - loss: 2.3012 - val_accuracy: 0.1135 - val_loss: 2.3010
Epoch 6/10
300/300 ━━━━━━━━━━━━━━━━━━━━ 317s 1s/step - accuracy: 0.1129 - loss: 2.3011 - val_accuracy: 0.1135 - val_loss: 2.3010
Epoch 7/10
300/300 ━━━━━━━━━━━━━━━━━━━━ 337s 1s/step - accuracy: 0.1118 - loss: 2.3013 - val_accuracy: 0.1135 - val_loss: 2.3010
Epoch 8/10
300/300 ━━━━━━━━━━━━━━━━━━━━ 378s 1s/step - accuracy: 0.1123 - loss: 2.3014 - val_accu

In [17]:
#evaluate model on test data
y_pred = vgg_model.predict(x_test)
y_pred_classes = np.argmax(y_pred, axis = 1)
y_true = np.argmax(y_test, axis = 1)

313/313 ━━━━━━━━━━━━━━━━━━━━ 13s 41ms/step


In [18]:
#confusion matrix, preicision, recall, f1 score
confusion = confusion_matrix(y_true, y_pred_classes)
precision = precision_score(y_true, y_pred_classes, average = 'weighted')
recall = recall_score(y_true, y_pred_classes, average = 'weighted')
f1 = f1_score(y_true, y_pred_classes, average = 'weighted')

print("Confusion Matrix:\n", confusion)
print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)


Confusion Matrix:
 [[   0  980    0    0    0    0    0    0    0    0]
 [   0 1135    0    0    0    0    0    0    0    0]
 [   0 1032    0    0    0    0    0    0    0    0]
 [   0 1010    0    0    0    0    0    0    0    0]
 [   0  982    0    0    0    0    0    0    0    0]
 [   0  892    0    0    0    0    0    0    0    0]
 [   0  958    0    0    0    0    0    0    0    0]
 [   0 1028    0    0    0    0    0    0    0    0]
 [   0  974    0    0    0    0    0    0    0    0]
 [   0 1009    0    0    0    0    0    0    0    0]]
Precision: 0.01288225
Recall: 0.1135
F1 Score: 0.023138302649304


y:\Python_installation\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
